### ISSUE TITLE
Deliveries where you always have to pay and will not deliver below a certain amount

### ISSUE THREAD

**Issue by bertso** [citymenu/clickandeat#100]
As I mentioned in the last email it won't, we need the restriction of no delivery below a certain amount but always charge for delivery. Something like

Minimum amount for delivery: (0 if you will always deliver)
Delivery charge: 3 euros
Minimum amount for free delivery (which obviously does not get used if the value in the first field is different than 0)
Allow deliveries below the minimum amount: (This will get over powered by the first field)

**Comment by mishimaltd** [comment]
OK I will rejig the data a bit, currently we have this:

1)  Minimum order for free delivery
2)  Delivery charge for orders under minimum value
3)  Allow delivery orders below minimum value

So instead I will have this:

1)  Minimum order value for delivery
2)  Delivery charge
3)  Allow delivery orders below minimum
4)  Free delivery for orders over minimum value

So setting option 4 to true for a restaurant would give us the same functionality that we have now, say if we currently say its free delivery for orders over £20 and delivery charge of £5 for orders under that amount we would set:

1: £20
2: £5
3: True
4: True

For a restaurant which charges £5 for delivery and won’t deliver an order under £20:

1: £20
2: £5
3: False
4: False

For a restaurant which has free delivery for orders over £20 but doesn’t allow orders under that amount we have:
1: £20
2: £0
3: False
4: True

**Comment by bertso** [comment]
Sorry I may have made things too complicated but let me know what you think
For this scenario I cannot configure it with your fields 
For a restaurant which charges £5 for delivery, does not allow orders below £15 and does free delivery for orders over £25
1) £152) £53) true4)

I seem to be missing an option
This is what I thought of1) Minimum order value for delivery
2) Delivery charge3) Allow Free delivery4) Minimum order value for Free delivery 
5) Allow delivery orders below minimum Free delivery

Free delivery for orders over £20 and delivery charge of £5 for orders under that amount we would set:1: £0
2: £5
3: True
4: £205: True For a restaurant which charges £5 for delivery and won’t deliver an order under £20:1: £20
2: £5
3: False
4: 05:False (not used)For a restaurant which has free delivery for orders over £20 but doesn’t allow orders under that amount we have:
1: £20
2: £0
3: True
4: £205: TrueFor a restaurant which charges £5 for delivery, does not allow orders below £15 and does free delivery for orders over £25
1: £15
2: £5
3: True
4: £255: True
Date: Mon, 17 Sep 2012 10:05:06 -0700

**Comment by mishimaltd** [comment]
Looks good mate

On 17 Sep 2012, at 18:22, bertso notifications@github.com wrote:

Sorry I may have made things too complicated but let me know what you think
For this scenario I cannot configure it with your fields
For a restaurant which charges £5 for delivery, does not allow orders below
£15 and does free delivery for orders over £25
1) £152) £53) true4)

I seem to be missing an option
This is what I thought of1) Minimum order value for delivery
2) Delivery charge3) Allow Free delivery4) Minimum order value for Free
delivery
5) Allow delivery orders below minimum Free delivery

Free delivery for orders over £20 and delivery charge of £5 for orders
under that amount we would set:1: £0
2: £5
3: True
4: £205: True For a restaurant which charges £5 for delivery and won’t
deliver an order under £20:1: £20
2: £5
3: False
4: 05:False (not used)For a restaurant which has free delivery for orders
over £20 but doesn’t allow orders under that amount we have:
1: £20
2: £0
3: True
4: £205: TrueFor a restaurant which charges £5 for delivery, does not allow
orders below £15 and does free delivery for orders over £25
1: £15
2: £5
3: True
4: £255: True
Date: Mon, 17 Sep 2012 10:05:06 -0700

**Comment by mishimaltd** [comment]
Fixed
