### ISSUE TITLE
Cuisines names

### ISSUE THREAD

**Issue by bertso** [citymenu/clickandeat#102]
Are they translatable or do we need to create a list for the cuisines in Spanish?

Americana
Argentina
Brasileña
Caribeña
China
Inglesa
Francesa
Griega
India
Italiana
Japonesa
Coreana
Libanésa
Mexicana
Medio Oriental
Nepalí
Oriental
Paquistaní
Peruana
Española
Siria
Tailandesa
Turca
Vietnamita

**Comment by mishimaltd** [comment]
Hi mate, they are in a properties file so yes we can translate them

**Comment by bertso** [comment]
Cool. Then I think we should make the change that I mentioned of only displaying the cuisines in the restaurants that the search has returned, there maybe names for cuisines in Spanish that never get used in English

Date: Wed, 19 Sep 2012 02:04:09 -0700

**Comment by mishimaltd** [comment]
It's ok let's make separate cuisine lists by language

On 19 Sep 2012, at 10:10, bertso notifications@github.com wrote:

Cool. Then I think we should make the change that I mentioned of only
displaying the cuisines in the restaurants that the search has returned,
there maybe names for cuisines in Spanish that never get used in English

Date: Wed, 19 Sep 2012 02:04:09 -0700

**Comment by bertso** [comment]
Makes sense

Date: Wed, 19 Sep 2012 02:13:38 -0700
