### ISSUE TITLE
Cuisines options

### ISSUE THREAD

**Issue by bertso** [citymenu/clickandeat#103]
Should we make the list of cuisines available based on the list of restaurants returned? This is to avoid to have too many options and every time they  click on one that its empty it brings/adds nothing

**Comment by mishimaltd** [comment]
Always show everything mate otherwise it will confuse people. The alternative is that we include text telling them that the list is truncated to cover only the available ones. I would prefer to just show all of them to be honest, the other sites do that and I think it generally makes sense

**Comment by bertso** [comment]
In my opinion if you are going to show all of them you should may be show the amount of restaurants in that cuisine? otherwise you may say 30 cuisines and there are only 5 of them represented in the results you potentially have 25 cuisines that when you click will bring nothing, kind of annoying. I know I am exaggerating a bit with the numbers but its to make the point :-)

Date: Wed, 19 Sep 2012 02:22:46 -0700
