### ISSUE TITLE
In subtype menu items the description appears to far down

### ISSUE THREAD

**Issue by bertso** [citymenu/clickandeat#105]
When creating a subtype and entering a description the description displays below the item name but at the same height than the row after the last subtype. It just looks odd.

Bagel category
http://clickandeat.herokuapp.com/restaurant.html?restaurantId=00000953

**Comment by mishimaltd** [comment]
Yeah I'll fix it so it's directly under the title

On 19 Sep 2012, at 10:39, bertso notifications@github.com wrote:

When creating a subtype and entering a description the description displays
below the item name but at the same height than the row after the last
subtype. It just looks odd.

Bagel category
http://clickandeat.herokuapp.com/restaurant.html?restaurantId=00000953

—
Reply to this email directly or view it on
GitHubhttps://github.com/mishimaltd/clickandeat/issues/105.

**Comment by mishimaltd** [comment]
I'll also put a bit more space between each individual item as they are a bit squished
