### ISSUE TITLE
Special instructions location

### ISSUE THREAD

**Issue by bertso** [citymenu/clickandeat#106]
If possible they would like the Special instructions box underneath the order at all times because when you are adding the food is when you think about them. Obviously this will then be transferred to the box in the checkout screen

**Comment by mishimaltd** [comment]
I'll add a button which opens a dialog that way they get the functionality without cluttering the UI

**Comment by bertso** [comment]
Other people put them underneath the order box, just a comment

Date: Wed, 19 Sep 2012 09:53:49 -0700

**Comment by mishimaltd** [comment]
They do it because they are fools sir

On 19 Sep 2012, at 18:09, bertso notifications@github.com wrote:

Other people put them underneath the order box, just a comment

Date: Wed, 19 Sep 2012 09:53:49 -0700

**Comment by bertso** [comment]
:-) 
:-) 

Date: Wed, 19 Sep 2012 10:28:56 -0700

**Comment by mishimaltd** [comment]
Done
