### ISSUE TITLE
SMS on decline

### ISSUE THREAD

**Issue by bertso** [citymenu/clickandeat#110]
What are the cost implications of this? I thought SMS where a no no, or am I getting confused with the twillio calls to mobiles?

"If you have provided a mobile number with your order you will receive an SMS message if your order is declined."

**Comment by mishimaltd** [comment]
Did I say that? It's not set in stone, let's discuss.

On 20 Sep 2012, at 14:18, bertso notifications@github.com wrote:

What are the cost implications of this? I thought SMS where a no no, or am
I getting confused with the twillio calls to mobiles?

"If you have provided a mobile number with your order you will receive an
SMS message if your order is declined."

—
Reply to this email directly or view it on
GitHubhttps://github.com/mishimaltd/clickandeat/issues/110.

**Comment by bertso** [comment]
I thought we had agreed to do something like some websites do, which is if you want to be notified by SMS it will cost you x tick the box, or something like, I guess for cancellations that is a bit mean, although that way we could setup a whole new business model based on cancellations :-)

Date: Thu, 20 Sep 2012 07:03:08 -0700

**Comment by mishimaltd** [comment]
We should SMS them if the order is declined and possibly if the order is accepted with a non-standard delivery time. I also think that if we have to auto-cancel the order we should SMS the user and give the user a discount of 10% off their next order in the email that we send them. If we don't do this it's unlikely they will use the site again.

**Comment by bertso** [comment]
10% is al our comission, it seems a bit nuts since it is the restaurants fault and it means we have to pay for their ineptitude.. maybe a 5% 

Date: Fri, 21 Sep 2012 01:18:30 -0700

**Comment by mishimaltd** [comment]
I think it's worth the hit to keep the customer to be honest. We will
delist the restaurant so these things won't pile up. If the customer has
made the effort to choose and come to our site I think we should bend over
backwards to keep them with us. It just means one order that we don't make
money on.

On 21 Sep 2012, at 09:37, bertso notifications@github.com wrote:

10% is al our comission, it seems a bit nuts since it is the restaurants
fault and it means we have to pay for their ineptitude.. maybe a 5%

Date: Fri, 21 Sep 2012 01:18:30 -0700

**Comment by mishimaltd** [comment]
Market share mate market share :-) the more user's we have on our site the more valuable the company seems. Even if we lose a few pence to keep a user with us, the valuation of the company is increased by much more than that by keeping them on board.

**Comment by mishimaltd** [comment]
Done, can you please translate the templaets

**Comment by bertso** [comment]
Yep

Date: Fri, 12 Oct 2012 13:44:30 -0700

**Comment by mishimaltd** [comment]
Thanks dude :-)

On 12 Oct 2012, at 21:47, bertso notifications@github.com wrote:

Yep

Date: Fri, 12 Oct 2012 13:44:30 -0700

**Comment by bertso** [comment]
Where are the templates you want me to translate? I have done a fetch and I cannot see anything

Date: Fri, 12 Oct 2012 13:47:44 -0700

**Comment by mishimaltd** [comment]
Sorry mate I am a numb nuts, have committed to GitHub now

On 12 Oct 2012, at 22:02, bertso notifications@github.com wrote:

Where are the templates you want me to translate? I have done a fetch and I
cannot see anything

Date: Fri, 12 Oct 2012 13:47:44 -0700

**Comment by mishimaltd** [comment]
Feel free to change the content as you wish, I’m not thinking too straight so the messages might not be great J

There is a 160 character limit for these SMS messages.

**Comment by bertso** [comment]
I am really sorry man but I just cannot find these templates that you are talking about, where are they?

Date: Fri, 12 Oct 2012 15:51:44 -0700

**Comment by mishimaltd** [comment]
We can sort it later mate, don't worry it will take you 2 minutes to do
once we sort out the repo. Currently the system will send you the text in
English if you enter a mobile number on checkout and the either decline the
order or let it auto cancel

Have set the payment gateway back to zero so it at least passes until we
get the other type set up

On 13 Oct 2012, at 09:15, bertso notifications@github.com wrote:

I am really sorry man but I just cannot find these templates that you are
talking about, where are they?

Date: Fri, 12 Oct 2012 15:51:44 -0700

**Comment by bertso** [comment]
Found them, found them.. I was expecting them to be out of Twillio.. what a knob..

Date: Sat, 13 Oct 2012 01:18:45 -0700

**Comment by bertso** [comment]
I've seen that you are offering a 10% of discount to the fella whose order has been rejected by the restaurant. Isn't that a bit of a nuts strategy? Maybe 5%, so that at least we make a 5% on their order :-) ? At the end of the day it is the restaurants fault..

Date: Sat, 13 Oct 2012 01:18:45 -0700

**Comment by mishimaltd** [comment]
Oh yeah :-) as I said feel free to change the text :-)

On 13 Oct 2012, at 09:26, bertso notifications@github.com wrote:

I've seen that you are offering a 10% of discount to the fella whose order
has been rejected by the restaurant. Isn't that a bit of a nuts strategy?
Maybe 5%, so that at least we make a 5% on their order :-) ? At the end of
the day it is the restaurants fault..

Date: Sat, 13 Oct 2012 01:18:45 -0700

**Comment by mishimaltd** [comment]
Crazy strategies are the key to success :-)

**Comment by bertso** [comment]
Do the accents etc need to be converted to unicode? If yes do I need to take into account all the characters, &#243;, for the character lenght count, or should I count this as one?

Date: Sat, 13 Oct 2012 01:18:45 -0700

**Comment by bertso** [comment]
On that account we are on our way to the very top!! Still waiting for sane one :-)

Date: Sat, 13 Oct 2012 01:32:49 -0700

**Comment by mishimaltd** [comment]
Try leaving it unescaped and we can test it

On 13 Oct 2012, at 09:40, bertso notifications@github.com wrote:

Do the accents etc need to be converted to unicode? If yes do I need to
take into account all the characters, &#243;, for the character lenght
count, or should I count this as one?

Date: Sat, 13 Oct 2012 01:18:45 -0700

**Comment by bertso** [comment]
OK

Date: Sat, 13 Oct 2012 01:45:14 -0700

**Comment by bertso** [comment]
I have all the other twillio ones escaped though.

Date: Sat, 13 Oct 2012 01:45:14 -0700

**Comment by mishimaltd** [comment]
Yeah I'm just not sure how the SMS system handles it. The phone call ones
get converted to XML first, I think SMS can probably handle special
characters automatically. Leave them in and we will know pretty soon :-) my
code can escape the template content either way so you definitely don't
need to

On 13 Oct 2012, at 10:10, bertso notifications@github.com wrote:

I have all the other twillio ones escaped though.

Date: Sat, 13 Oct 2012 01:45:14 -0700
