### ISSUE TITLE
When receiving the Twillio call as a restaurant if press any key to listen to the order it hangs up

### ISSUE THREAD

**Issue by bertso** [citymenu/clickandeat#111]
I have tried this twice and it has happened both times. I listen to the initial message and it says press any key if I want to listen to the order and as soon as I press any key, not the hanging up one obviously, it hangs up. Basically I am not able to listen to the order on the phone, I've been able to do this before.

**Comment by mishimaltd** [comment]
I'll check the code mate

On 20 Sep 2012, at 15:04, bertso notifications@github.com wrote:

I have tried this twice and it has happened both times. I listen to the
initial message and it says press any key if I want to listen to the order
and as soon as I press any key, not the hanging up one obviously, it hangs
up. Basically I am not able to listen to the order on the phone, I've been
able to do this before.

—
Reply to this email directly or view it on
GitHubhttps://github.com/mishimaltd/clickandeat/issues/111.

**Comment by mishimaltd** [comment]
I will fix the system to escape special characters differently for xml and also fix the order status fail callback so that it works

**Comment by mishimaltd** [comment]
Can you test again please?

**Comment by mishimaltd** [comment]
Closing, raise new ticket if it happens again
