### ISSUE TITLE
Is the cancellation email and the 20min email active

### ISSUE THREAD

**Issue by bertso** [citymenu/clickandeat#113]
Are those two functionalities in place? I haven't received either of those emails for orders placed

**Comment by mishimaltd** [comment]
Is the restaurant currently open?

On 20 Sep 2012, at 15:13, bertso notifications@github.com wrote:

Are those two functionalities in place? I haven't received either of those
emails for orders placed

—
Reply to this email directly or view it on
GitHubhttps://github.com/mishimaltd/clickandeat/issues/113.

**Comment by bertso** [comment]
Yep, between 10:00 and 22:00 hours

http://clickandeat.herokuapp.com/admin/restaurants/edit.html?restaurantId=00000962
Date: Thu, 20 Sep 2012 07:28:10 -0700

**Comment by mishimaltd** [comment]
I will check what is going on with the timings. Might be some daft UTC thing I left in

**Comment by mishimaltd** [comment]
The timings are fine its the scheduled process was not running. I will either find a way to only ever run on one instance or change the redis put logic to handle this situation.

**Comment by mishimaltd** [comment]
Move the logic out of the Abstract clustered task into the main class and re-introduce the original locking, it was better. Make sure it unlocks itself if there are any issues, maybe set the lock object to only live for 5 minutes?

**Comment by mishimaltd** [comment]
Distributed locking:

https://github.com/abelaska/jedis-lock/blob/master/src/main/java/com/github/jedis/lock/JedisLock.java

**Comment by mishimaltd** [comment]
Fixed
