### ISSUE TITLE
The email that confirms that the order has been accepted did not contain delivery time

### ISSUE THREAD

**Issue by bertso** [citymenu/clickandeat#114]
I selected option 3 and a delivery time of 55mins, everything went smoothly but the email that I received didn't mention the 55mins.

As an enhancement would it be easy to add a link in that email, if the time is greater than the one specified in the restaurant document, to allow them cancelling the order?

**Comment by mishimaltd** [comment]
Yes we can add that and I'll put in all the delivery stuff when we decide on the email content. I'll add that time in as a starting point anyway

**Comment by mishimaltd** [comment]
All done
