### ISSUE TITLE
delisting email does not contain link to enlist again

### ISSUE THREAD

**Issue by bertso** [citymenu/clickandeat#116]

**Comment by mishimaltd** [comment]
Again, not implemented yet. Should we do a phone call for relisting as well? Maybe they can't read their email or something. We can go with an email only to start with and then if we get problems add the call I guess

**Comment by bertso** [comment]
Yeah, probably a call would make sense, I doubt that if they are busy they will check their email..

Date: Thu, 20 Sep 2012 08:13:17 -0700

**Comment by mishimaltd** [comment]
The email contains a link now

**Comment by mishimaltd** [comment]
Working
