### ISSUE TITLE
Cutoff time for non standard delivery should be a small configured amount like 15 mins

### ISSUE THREAD

**Issue by mishimaltd** [citymenu/clickandeat#117]

**Comment by bertso** [comment]
What is this?

Date: Thu, 20 Sep 2012 16:56:31 -0700

**Comment by mishimaltd** [comment]
I have set it so that if the restaurant has standard delivery of 45 minutes but responds to an order saying it will be ready in 90 minutes then the customer has 90 - 45 = 45 minutes window in which they can cancel the order. I think this window is too long for the restaurant so want to just default it to 10 or 15 minutes. That way we tell the restaurant that if they select a non-standard delivery time they need to be aware that the customer may cancel the order in the next 10 minutes rather than have some wierd time window based on the restaurant's own standard delivery time.

**Comment by bertso** [comment]
Make sense. How would the restaurant we notified of the cancellation? If it is a Twillio call it should say first Cancellation from llamarYComer so that they don't press any key to listen to the order. Plus email and maybe sms.

Date: Fri, 21 Sep 2012 01:16:33 -0700

**Comment by mishimaltd** [comment]
They get an email if the order is cancelled but yes I think they should get
a call too

On 21 Sep 2012, at 09:35, bertso notifications@github.com wrote:

Make sense. How would the restaurant we notified of the cancellation? If it
is a Twillio call it should say first Cancellation from llamarYComer so
that they don't press any key to listen to the order. Plus email and maybe
sms.

Date: Fri, 21 Sep 2012 01:16:33 -0700

**Comment by mishimaltd** [comment]
Done
