### ISSUE TITLE
Do we need a standard time for collection the same as we have one for delivery?

### ISSUE THREAD

**Issue by mishimaltd** [citymenu/clickandeat#118]

**Comment by bertso** [comment]
What do you mean? If the person should be told at what time they should come to collect the order? If that is the case I believe we do.

Date: Thu, 20 Sep 2012 23:19:56 -0700

**Comment by mishimaltd** [comment]
Lets have a standard collection time for restaurants same as we do for delivery.

**Comment by bertso** [comment]
Yep

Date: Fri, 21 Sep 2012 01:14:31 -0700

**Comment by mishimaltd** [comment]
Will integrate this in the same way as for delivery. Will set default values of 45 mins and 20 mins for delivery/collection time but obviously the restaurant record can be edited to set specific values. Will make these values compulsory on the admin section. Will update order panel to just show ASAP as an allowed delivery time today once the current time is greater than the closing time minus the standard time.

**Comment by mishimaltd** [comment]
Fixed
