### ISSUE TITLE
If a restaurant closes for delivery at 11pm and their delivery time is 45mins can I book a delivery for 11:45 since an order booked at 11pm would not arrive until then?

### ISSUE THREAD

**Issue by mishimaltd** [citymenu/clickandeat#119]

**Comment by bertso** [comment]
I'll try to find this out but I am assuming they will take this into consideration when they specify the delivery times, they don't necessarily mean the times the restaurant is open or close, they should be the times when they will get the last orders for cooking, me thinks.

Date: Thu, 20 Sep 2012 23:22:00 -0700

**Comment by mishimaltd** [comment]
I'll set the app so that if the closing time for the restaurant is say 11pm
and it is now something like 10:45 pm then the only delivery time you can
select for today is ASAP rather than 11:15pm etc. I think this will make
sense to users and restaurants

On 21 Sep 2012, at 08:58, bertso notifications@github.com wrote:

I'll try to find this out but I am assuming they will take this into
consideration when they specify the delivery times, they don't necessarily
mean the times the restaurant is open or close, they should be the times
when they will get the last orders for cooking, me thinks.

Date: Thu, 20 Sep 2012 23:22:00 -0700

**Comment by bertso** [comment]
Just got this confirm. Restaurants should specify 1-2 hours before they actually closed. This is what I was told so if restaurant closes at 11:00, last time lets make it 11:45

**Comment by mishimaltd** [comment]
Hi Mate. I think if I do my ASAP thing then its a lot easier for everyone to understand and provides the same functionality. The restaurant just sets the delivery closing time to be the time they stop taking delivery orders. It will work

**Comment by mishimaltd** [comment]
Fixed
