### ISSUE TITLE
Validation for the restaurant telephone number field

### ISSUE THREAD

**Issue by bertso** [citymenu/clickandeat#121]
I am such a twat, I have been testing a restaurant with no telephone number in it and spent ages looking at the telephone, ring f****er, ring!, check the volume etc and finally looked at the Twillio log, no too helpful this time and then check the restaurant document..

**Comment by mishimaltd** [comment]
Poor bertso :-)

What was the name of that font they wanted? I am cool with all the
scrolling stuff now :-)

On 21 Sep 2012, at 14:13, bertso notifications@github.com wrote:

I am such a twat, I have been testing a restaurant with no telephone number
in it and spent ages looking at the telephone, ring f****er, ring!, check
the volume etc and finally looked at the Twillio log, no too helpful this
time and then check the restaurant document..

—
Reply to this email directly or view it on
GitHubhttps://github.com/mishimaltd/clickandeat/issues/121.

**Comment by bertso** [comment]
I've seen the code and it looks pretty doable. The font was "maiandra gd", he is looking into it as we email. The site its a bit crap, you cannot show all the fonts in one go, you have to keep on pressing load more fonts etc.

Date: Fri, 21 Sep 2012 06:27:17 -0700
