### ISSUE TITLE
Set containers so that order panel always fits inside

### ISSUE THREAD

**Issue by mishimaltd** [citymenu/clickandeat#123]

**Comment by bertso** [comment]
Is this related to the fact that when the order is too long the content goes underneath the footer? If it's not we need to create another issue for that.

**Comment by mishimaltd** [comment]
Yeah it's that issue :-)

On 28 Sep 2012, at 10:49, bertso notifications@github.com wrote:

Is this related to the fact that when the order is too long the content
goes underneath the footer? If it's not we need to create another issue for
that.

—
Reply to this email directly or view it on
GitHubhttps://github.com/mishimaltd/clickandeat/issues/123#issuecomment-8969367.

**Comment by mishimaltd** [comment]
Fixed
