### ISSUE TITLE
When in the checkout page, in long orders, I miss a portion of the your order box

### ISSUE THREAD

**Issue by bertso** [citymenu/clickandeat#127]
If the order is quite long when in  the checkout page I cannot see the elements of the order that go below the footer. The your order should push the footer down.
This also happens in the payment page

**Comment by mishimaltd** [comment]
Will update so that the order panel is only floating up and down on the menu page. Also on the menu page add event handler to ensure the containing div is big enough to hold the order panel. Check around adding a new item when the panel is parked at the bottom as this seems to be not quite working.
