### ISSUE TITLE
Remind the restaurant that the user can cancel the order if they extend their standard delivery time

### ISSUE THREAD

**Issue by bertso** [citymenu/clickandeat#128]
Should we add some text to tell the Restaurant that if they select a time greater than their standard delivery time the customer will have (X) minutes where he\she can cancel the order

Your standard delivery time is: 45 minutes
Click below to add additional time beyond your standard delivery time for this order
[ REMEMBER THE USER WILL HAVE 10 MINUTES TO DECIDE IF THEY WANT TO STILL GO AHEAD WITH THE ORDER ]
Plus 15 minutes
Plus 30 minutes
Plus 45 minutes
Plus 60 minutes
Plus 90 minutes
Plus 120 minutes

**Comment by mishimaltd** [comment]
Yeah I like that

On 24 Sep 2012, at 14:15, bertso notifications@github.com wrote:

Should we add some text to tell the Restaurant that if they select a time
greater than their standard delivery time the customer will have (X)
minutes where he\she can cancel the order

Your standard delivery time is: 45 minutes
Click below to add additional time beyond your standard delivery time for
this order
[ REMEMBER THE USER WILL HAVE 10 MINUTES TO DECIDE IF THEY WANT TO STILL GO
AHEAD WITH THE ORDER ]
Plus 15 minutes
Plus 30 minutes
Plus 45 minutes
Plus 60 minutes
Plus 90 minutes
Plus 120 minutes

—
Reply to this email directly or view it on
GitHubhttps://github.com/mishimaltd/clickandeat/issues/128.

**Comment by mishimaltd** [comment]
Its on the email they get
