### ISSUE TITLE
Discounts 

### ISSUE THREAD

**Issue by mishimaltd** [citymenu/clickandeat#134]
I have put the discounts on the order panel. Can you add some discounts to a restaurant including a free item one and test. Am thinking the info should be at the top if the panel not the bottom

**Comment by bertso** [comment]
I'll check it. Based on their comments they said that the order is the main thing and that the discounts should be at the bottom. At the beginning of the ordering process you will see everything so you can scan the offers and then they can take a secondary role, you know where they are so you can always go to the bottom of the your order and check them again, 

Date: Tue, 25 Sep 2012 00:17:50 -0700

**Comment by mishimaltd** [comment]
Excellent, that's where they are now. Let me know if you think the select
box for a free item should appear in the menu items bit or the discounts
bit. Currently it's in the discounts bit

On 25 Sep 2012, at 08:48, bertso notifications@github.com wrote:

I'll check it. Based on their comments they said that the order is the main
thing and that the discounts should be at the bottom. At the beginning of
the ordering process you will see everything so you can scan the offers and
then they can take a secondary role, you know where they are so you can
always go to the bottom of the your order and check them again,

Date: Tue, 25 Sep 2012 00:17:50 -0700

**Comment by mishimaltd** [comment]
I'll move the drop-down select so that it is inside the items list if the discount is applicable
