### ISSUE TITLE
Menu elements sorted by price

### ISSUE THREAD

**Issue by bertso** [citymenu/clickandeat#135]
They were saying that it would make sense if we could sort the menu elements by price within each menu category and display them from cheapest to most expensive. In the end we all look for the cheapest options to see if there is anything we like before moving to the most expensive, don't we? We need to find ways to differentiate ourselves from the competition and I guess if we make a navigation that customers find easier to use than the competition we are in the right track. I was thinking if this could be done at db level when the menu items are being inserted hence the calculation only gets done the once.
Again, this is not a priority, it is a nice feature.

**Comment by mishimaltd** [comment]
I've implemented drag and drop ordering for menu items in the admin section. It would be a shame to lose this functionality I think. Lets leave this one for now if that's OK. Happy to come back to it so leave the issue open

**Comment by bertso** [comment]
Can we have a button in the admin where you say sort all by price. Then you don't force the sorting by price? Or even on the site, so the user decides if that is something they find useful?

Date: Tue, 25 Sep 2012 02:12:29 -0700

**Comment by mishimaltd** [comment]
Closing for now
