### ISSUE TITLE
Need to define and incorporate Terms and Conditions

### ISSUE THREAD

**Issue by mishimaltd** [citymenu/clickandeat#14]
Covering use of the Website, disclaimers, our commitment to customers and policies. The stuff for restaurants we don't necessarily need on the site itself as we can just make them aware if they want to sign up. 

Maybe we can just look at what the other sites have, see if they have a lot in common and if so then this is probably the approach we should take since it must be working reasonably well for them.

**Comment by bertso** [comment]
We can go with the Justeat as a template for ours

**Comment by mishimaltd** [comment]
Cool, I'll look at just eat and hungry house and merge the texts a bit so it comes across as original and I can get the best parts of each. Do you think you or one of the others might be able to get hold of the T&Cs that just eat have with their restaurants?

-----Original Message-----

**Comment by bertso** [comment]
I will raise the issue in tonight's meeting.

**Comment by bertso** [comment]
Don't do anything yet. I have found through my friend that has replicated Groupon that we should be OK to get a payment gateway in Spain without all this third party problems. Basically if we are going to do any documents will probably end up being in Spanish so it is pointless for you to spend your time doing this. The only things that they asked him was a link to their website and a sales forecast. I have asked the guys in Spain to speed up the process of getting the payment gateway.

**Comment by mishimaltd** [comment]
That is wicked news on so many levels :-)

**Comment by mishimaltd** [comment]
Not us doing this
