### ISSUE TITLE
Cannot call spanish numbers

### ISSUE THREAD

**Issue by bertso** [citymenu/clickandeat#140]
Tonight we were trying to make a demo using one of their landline phones and it didn't work. The funny thing is that Twillio has no logging referring to these phone calls..

**Comment by mishimaltd** [comment]
Hi mate that is odd it has costs for Spain so should definitely support it,
I'll find out why it didn't connect

On 26 Sep 2012, at 22:28, bertso notifications@github.com wrote:

Tonight we were trying to make a demo using one of their landline phones
and it didn't work. The funny thing is that Twillio has no logging
referring to these phone calls..

—
Reply to this email directly or view it on
GitHubhttps://github.com/mishimaltd/clickandeat/issues/140.

**Comment by mishimaltd** [comment]
Which restaurant did you use? I can't see any with a Spanish number

On 26 Sep 2012, at 22:28, bertso notifications@github.com wrote:

Tonight we were trying to make a demo using one of their landline phones
and it didn't work. The funny thing is that Twillio has no logging
referring to these phone calls..

—
Reply to this email directly or view it on
GitHubhttps://github.com/mishimaltd/clickandeat/issues/140.

**Comment by bertso** [comment]
It was Txurreria bla. We changed the number back to confirm that still worked with UK numbers. I am going to be testing it with my parents or some family in Spain later

**Comment by bertso** [comment]
Are the menu and your order boxes final or an interim step to some awesome design? I really like the shadow that you've added to the opening times and delivery summary, it smartens them up.
Another comment, the designer is asking me what about the design he sent for the home. I've just said that we will finish the functionality in the home and then we can all start discussing the design, what do you think me man?

**Comment by mishimaltd** [comment]
Yep sounds good thanks I thought the boxes would match the restaurant

**Comment by bertso** [comment]
What do you mean much the restaurant? You were thinking on putting a box like that round the restaurant details?

**Comment by mishimaltd** [comment]
Do you think I should?

**Comment by bertso** [comment]
To be honest I am not that keen on the new boxes round the "Your Order" and "Menu", I'll rather have them similar to the "Opening Times", but who am I to say.. Should I as the designer for his opinion..?

**Comment by mishimaltd** [comment]
Yeah ask him I like them more than the rounded ones

**Comment by bertso** [comment]
This is still playing up. I have been trying this morning to use it and it doesn't work again. We may have to ask them if we need to make a formal request. Let me know how do you interpret the making a request bit in this page. 
https://www.twilio.com/user/account/international

Last night the software worked but not 100% correctly, you can see in the log that there are some phone calls to Spain. They will accept an order and the system will send the 5 minute cancelling email and will also auto cancel the order after 20 mins, and we did have the accept order email obtained when you press 1#. All a bit strange. 

I will test last night combinations with a UK number and confirm that everything is working as expected.

**Comment by mishimaltd** [comment]
Thanks mate ill look at the Twilio bit

On 28 Sep 2012, at 10:19, bertso notifications@github.com wrote:

This is still playing up. I have been trying this morning to use it and it
doesn't work again. We may have to ask them if we need to make a formal
request. Let me know how do you interpret the making a request bit in this
page.
https://www.twilio.com/user/account/international

Last night the software worked but not 100% correctly, you can see in the
log that there are some phone calls to Spain. They will accept an order and
the system will send the 5 minute cancelling email and will also auto
cancel the order after 20 mins, and we did have the accept order email
obtained when you press 1#. All a bit strange.

I will test last night combinations with a UK number and confirm that
everything is working as expected.

—
Reply to this email directly or view it on
GitHubhttps://github.com/mishimaltd/clickandeat/issues/140#issuecomment-8968798.

**Comment by mishimaltd** [comment]
I filled in that form with some basic details and using my company name.
Their support team will follow up with me so ill take it from there

On 28 Sep 2012, at 10:19, bertso notifications@github.com wrote:

This is still playing up. I have been trying this morning to use it and it
doesn't work again. We may have to ask them if we need to make a formal
request. Let me know how do you interpret the making a request bit in this
page.
https://www.twilio.com/user/account/international

Last night the software worked but not 100% correctly, you can see in the
log that there are some phone calls to Spain. They will accept an order and
the system will send the 5 minute cancelling email and will also auto
cancel the order after 20 mins, and we did have the accept order email
obtained when you press 1#. All a bit strange.

I will test last night combinations with a UK number and confirm that
everything is working as expected.

—
Reply to this email directly or view it on
GitHubhttps://github.com/mishimaltd/clickandeat/issues/140#issuecomment-8968798.

**Comment by bertso** [comment]
Was your interpretation that you had to do that then? My initial one was but the fact that Yesterday I selected Spain and I manage to make a few calls got me confused.Cheers

**Comment by mishimaltd** [comment]
It's wierd I figure may as well do the form then I can follow up getting
then to sort out why it doesn't work all the time

On 28 Sep 2012, at 10:42, bertso notifications@github.com wrote:

Was your interpretation that you had to do that then? My initial one was
but the fact that Yesterday I selected Spain and I manage to make a few
calls got me confused.Cheers

—
Reply to this email directly or view it on
GitHubhttps://github.com/mishimaltd/clickandeat/issues/140#issuecomment-8969230.

**Comment by mishimaltd** [comment]
Hopefully all done and fixed now

**Comment by bertso** [comment]
about to test this

Date: Mon, 1 Oct 2012 02:25:35 -0700
