### ISSUE TITLE
Restaurant document not refreshing changes

### ISSUE THREAD

**Issue by bertso** [citymenu/clickandeat#142]
I am in Xurreria Trebol, in the admin document I select Thursday to be closed and when I refresh the document on the web it still shows as opened. Could this be something to do with the cache? Basically is not looking for the restaurant details again, its just reading them from the cache?

The weird thing is that if I open the restaurant in firefox it displays as closed? Are objects being cached in the browser?

**Comment by mishimaltd** [comment]
I think you need to modify the order for the change to be reflected

On 27 Sep 2012, at 10:23, bertso notifications@github.com wrote:

I am in Xurreria Trebol, in the admin document I select Thursday to be
closed and when I refresh the document on the web it still shows as opened.
Could this be something to do with the cache? Basically is not looking for
the restaurant details again, its just reading them from the cache?

The weird thing is that if I open the restaurant in firefox it displays as
closed? Are objects being cached in the browser?

—
Reply to this email directly or view it on
GitHubhttps://github.com/mishimaltd/clickandeat/issues/142.

**Comment by bertso** [comment]
But if I open the link in a different browser it opens properly, with the open or close displaying the right value. Shouldn't this happen also when I refresh?I come out of the restaurant document to the list and come back in, and still doesn't display the change correctly. What if I am in the restaurant 1 min before they open and I am desperate to have a churro from them and I keep on refreshing like crazy and keeps on telling me that it is closed when the restaurant details says that it should be open at 11? Do I need to go without my favorite churro?? Come on man, I want my churro!!

Date: Thu, 27 Sep 2012 02:49:36 -0700

**Comment by mishimaltd** [comment]
Fixed
