### ISSUE TITLE
Basket(Order) when moving from one restaurant to another

### ISSUE THREAD

**Issue by bertso** [citymenu/clickandeat#15]
While looking at the code I realized that if you move from one restaurant to another ( !restaurantId.equals(order.getRestaurantId())) the order items are removed, which I thinks its a good idea. There is a slight issue when you first open the second restaurant and that is that the order from the previous one still displays and it may be confusing. Only when you click the add link to add something different the order clears. It maybe a good idea not to clear it until they press add but then we shouldn't show the order from the previous restaurant while in the new one I think it will be confussing. Basically: 
 !restaurantId.equals(order.getRestaurantId()) just show an empty basket.

**Comment by mishimaltd** [comment]
What I was intending to do is to include the restaurant name in that order thing so it will say something like ('Your order with Domino's Pizza') and then if they open another restaurant menu, when they click to add an item it will come up with a warning saying ('You are already building an order with Domino's Pizza, you can only order from one Restaurant at a time, if you add this item to your order, all order items for Domino's Pizza will be removed from your order, do you want to proceed?). Or something a bit more succinct if possible :-)

**Comment by bertso** [comment]
That sounds the business to me :-)

**Comment by mishimaltd** [comment]
Done the confirmation dialog. Text content and general formatting to sort once we have the whole look and feel sorted.
