### ISSUE TITLE
Message/div whatever to present when the address entered in homepage has no matches

### ISSUE THREAD

**Issue by bertso** [citymenu/clickandeat#150]
We need to create a div or dialog or something to notify the user that there are no restaurants offering a service for the address entered in the homepage.

**Comment by mishimaltd** [comment]
Yeah we need something like, sorry do not currently have any restaurants serving this location, please check back as we are adding new locations all the time, maybe give them the option to register but I seriously doubt that they would

**Comment by bertso** [comment]
No need for registering yet, but at least let them know that there are no restaurants serving in the area. The registering can happen in V2 when doing the pyramid stuff.

Date: Wed, 3 Oct 2012 02:23:07 -0700

**Comment by mishimaltd** [comment]
Done
