### ISSUE TITLE
Homepage - search to be triggered by pressing the enter key

### ISSUE THREAD

**Issue by bertso** [citymenu/clickandeat#151]
in the mepage they want the cursor to go straight away to the search field and then the search to be triggered by just pressing enter. Both of these requests make perfect sense.

**Comment by mishimaltd** [comment]
This is no problem at all. Do they have any better ideas than that butler with the thought bubble on what to put on the home page? I think that maybe that slidedeck thing we could use to say how it works then we just have a couple of boxes, one mentioning the magazine and one advertising for restaurant owners to sign up.

For browsing by cuisine/location, we could put this information in the footer to start with

**Comment by bertso** [comment]
I think that the designer is waiting for all the functionality to be finished to come back with his suggested homepage, which I have the feeling that it will be along the lines of what he sent last time. I think that maybe we need to agree on what should be in the home page and then maybe let him design something that presents all that info.
I think we need:
[M]: Must have

Header
1) [M] Header with company name and Logo (something including the butler, maybe the one with the laptop instead of the one ringing the bell to differentiate the site from the magazine) 

Body
2) [M] Search box
3) [O](Optional) Cuisines options
4) [O](Optional) Instructions. I am assuming that anyone that arrives to the site will know how they work. But if we can do something nice I think it may be worth having
5) [O](Optional) Food pictures. My mate really wants to have food pictures. I am not sure that they are necessary. I think a cool alternative could be some cartoonish graphic from the designer with the butler cooking something. Or a couple of them, one with a Chinese outfit and another one with a pizza or something like that.

Footer
6) [M] Terms and Conditions
7) [M] Links to a page or a pdf that explains to the restaurants how to join us
8) [M] Company info
9) [O](Optional) Links to cuisines searches, for the search crawlers
10) [O](Optional) Links to Twitter, Facebook, etc if they are going to provide a social media service. This is a tricky one because if no one is responsible for it, it could do more harm than help.

This is a starting point. Like always, add, remove, comment etc and I will pass it on.
Cheers 

Date: Wed, 3 Oct 2012 02:24:40 -0700
