### ISSUE TITLE
Cuisine types are coming out of the "Choose a cuisine" div

### ISSUE THREAD

**Issue by bertso** [citymenu/clickandeat#153]
Some of the cuisine types are spreading out of the "Choose a cuisine" div. This is due to some of the names holding two options "Spanish \ Mediterranean". This could be solved by including spaces or changing this into two different options, but could it be fixed differently just in case it happens with a type of cuisine, or is it not worth the hustle? I have sent you a jpeg to your email

**Comment by bertso** [comment]
f it, I think we remove the "/" and we use "and", or we create two different categories

**Comment by mishimaltd** [comment]
Hi mate, yeah I have seen that :-) It's because it can't break the line so it can't do very much with it. I think we need to just put a space each side of the / character to start with for now.

**Comment by mishimaltd** [comment]
Create 2 categories as a restaurant can be in more than one anyway

On 3 Oct 2012, at 11:24, bertso notifications@github.com wrote:

f it, I think we remove the "/" and we use "and", or we create two
different categories

—
Reply to this email directly or view it on
GitHubhttps://github.com/mishimaltd/clickandeat/issues/153#issuecomment-9101698.
