### ISSUE TITLE
Displaying the Restaurant name with whom you have the order when not in the restaurant paget

### ISSUE THREAD

**Issue by bertso** [citymenu/clickandeat#160]
When in the search results page if there is an order displaying it should display the name of the restaurant that the order belongs to.

**Comment by mishimaltd** [comment]
Yeah I was going to add that :-)

On 6 Oct 2012, at 21:34, bertso notifications@github.com wrote:

When in the search results page if there is an order displaying it should
display the name of the restaurant that the order belongs to.

—
Reply to this email directly or view it on
GitHubhttps://github.com/mishimaltd/clickandeat/issues/160.

**Comment by mishimaltd** [comment]
Done
