### ISSUE TITLE
Should we prevent user checkout if we can't validate the users address?

### ISSUE THREAD

**Issue by mishimaltd** [citymenu/clickandeat#180]
Maybe just validate postcode? I don't want to lose an order because the address is typed in funny

**Comment by bertso** [comment]
If we don't prevent it at least display a massive message telling them so. I guess google api is not infalable but usually its right :-)
Date: Tue, 9 Oct 2012 22:57:31 -0700

**Comment by mishimaltd** [comment]
Not validating address as I don't want to cause the user not to be able to put in an order. have added restaurant decline option to the email where they can say that they don't deliver to that address
