### ISSUE TITLE
Displaying the restaurants that don't accept online payments

### ISSUE THREAD

**Issue by bertso** [citymenu/clickandeat#186]
Since with the new strategy no we are going to display restaurants that don't accept online payments there is the following suggestion about how to go about it.

When returning the search results we only display the restaurants that accept online payments. At the end of the last one we have another section where those that do not accept online payments are display with a different icon. The user can decide to display them or not. 

The following Spanish website is doing that
http://www.laneveraroja.com

**Comment by mishimaltd** [comment]
I've done the integrating the registration stuff, can you translate the couple of bits of English I have put into the spanish page please

**Comment by bertso** [comment]
Done

Date: Sat, 20 Oct 2012 15:20:27 -0700

**Comment by mishimaltd** [comment]
Done
