### ISSUE TITLE
Location of discount vouchers

### ISSUE THREAD

**Issue by bertso** [citymenu/clickandeat#195]
They want the discount voucher at the top of the P4 (checkout). I can do this if you want

**Comment by mishimaltd** [comment]
Ok :-)

On 18 Oct 2012, at 10:49, bertso notifications@github.com wrote:

They want the discount voucher at the top of the P4 (checkout). I can do
this if you want

—
Reply to this email directly or view it on
GitHubhttps://github.com/mishimaltd/clickandeat/issues/195.

**Comment by bertso** [comment]
Done
