### ISSUE TITLE
They want the last name field to be optional

### ISSUE THREAD

**Issue by bertso** [citymenu/clickandeat#196]
They want the last name field to be optional. I can do this if you want

**Comment by mishimaltd** [comment]
Cool

On 18 Oct 2012, at 10:50, bertso notifications@github.com wrote:

They want the last name field to be optional. I can do this if you want

—
Reply to this email directly or view it on
GitHubhttps://github.com/mishimaltd/clickandeat/issues/196.

**Comment by bertso** [comment]
Done
