### ISSUE TITLE
Reduce width of homepage bubble by about 30px

### ISSUE THREAD

**Issue by mishimaltd** [citymenu/clickandeat#197]
Will be big enough still to hold just about anything.

Get rid of chrome focus border too

**Comment by bertso** [comment]
Yeah baby, it looks as if its going to eat our scooter riding butler :-)

Date: Fri, 19 Oct 2012 00:49:04 -0700

**Comment by mishimaltd** [comment]
Yeah I can tweak it now so It is no bigger than we need to hold a decent
sized search bar.

Now it's not so tall we can put some stuff on the page under it, do you or
your amigos have any thoughts or preferences on that?

On 19 Oct 2012, at 08:53, bertso notifications@github.com wrote:

Yeah baby, it looks as if its going to eat our scooter riding butler :-)

Date: Fri, 19 Oct 2012 00:49:04 -0700

**Comment by bertso** [comment]
I have a feeling that we may need to put the 2 boxes you mentioned ourselves with the lore simposium or whatever and then push for the content. Alternatively we can put the steps on how the site works for the time being and maybe change it once there is other content.

Date: Fri, 19 Oct 2012 00:59:01 -0700

**Comment by mishimaltd** [comment]
Sure mate.

Do you mind re-testing sending SMS to Spanish mobile again please?

On 19 Oct 2012, at 09:06, bertso notifications@github.com wrote:

I have a feeling that we may need to put the 2 boxes you mentioned
ourselves with the lore simposium or whatever and then push for the
content. Alternatively we can put the steps on how the site works for the
time being and maybe change it once there is other content.

Date: Fri, 19 Oct 2012 00:59:01 -0700

**Comment by bertso** [comment]
Sure.

Date: Fri, 19 Oct 2012 01:16:01 -0700
