### ISSUE TITLE
Check delivery time consistency

### ISSUE THREAD

**Issue by mishimaltd** [citymenu/clickandeat#199]
Email vs Twilio on non standard times for collection and delivery

**Comment by bertso** [comment]
May be both? The email is still necessary so that they can cancel the order, the SMS will make them aware faster.

Date: Fri, 19 Oct 2012 05:54:39 -0700

**Comment by mishimaltd** [comment]
Hi mate

Yes we need both this is just to confirm that the behaviour is the same for
both

On 19 Oct 2012, at 13:59, bertso notifications@github.com wrote:

May be both? The email is still necessary so that they can cancel the
order, the SMS will make them aware faster.

Date: Fri, 19 Oct 2012 05:54:39 -0700

**Comment by bertso** [comment]
ok

Date: Fri, 19 Oct 2012 06:05:35 -0700
