### ISSUE TITLE
SEO

### ISSUE THREAD

**Issue by bertso** [citymenu/clickandeat#202]
We should try to implement the following:

1) The links used to open restaurants should contain, if possible, 
    + Takeaway food (if this could be configured at message.properties file even better. Multilingual)
    + City where the restaurant is located
    + Name of the restaurant (this could be tricky with the Spanish characters)
  I guess the restaurant id needs to go somewhere, but that it something that is not needed by the SEO.

2) The search results links, again it will be good if they contain:
    + Takeaway food (if this could be configured at message.properties file even better. Multilingual)
    + City where the restaurant is located
    + Maybe postcode

3) Links to open restaurants and do searches by cities, cuisines, again it will be good if they contain:
    + Takeaway food (if this could be configured at message.properties file even better. Multilingual)
    + Cuisine name
    + City name

**Comment by mishimaltd** [comment]
Add this tracking code to all pages:

<script type="text/javascript">
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-34980612-1']);
  _gaq.push(['_trackPageview']);
  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
</script>

**Comment by bertso** [comment]
Where would this information be stored?

Date: Thu, 1 Nov 2012 07:31:32 -0700

**Comment by mishimaltd** [comment]
On google Analytics site. It's really good, shows you everything. We don't
need to add any page view tracking beyond this

On 1 Nov 2012, at 14:49, bertso notifications@github.com wrote:

Where would this information be stored?

Date: Thu, 1 Nov 2012 07:31:32 -0700

**Comment by bertso** [comment]
Cool. Are you have you configured this in the llamarYcomer domain or in the clickandeat one?

Date: Thu, 1 Nov 2012 07:50:36 -0700

**Comment by bertso** [comment]
I am assuming it doesn't matter, Analytics will determine where it came from.. donkey old me

Date: Thu, 1 Nov 2012 07:50:36 -0700

**Comment by mishimaltd** [comment]
Llamarycomer

On 1 Nov 2012, at 14:52, bertso notifications@github.com wrote:

Cool. Are you have you configured this in the llamarYcomer domain or in the
clickandeat one?

Date: Thu, 1 Nov 2012 07:50:36 -0700

**Comment by bertso** [comment]
Are we going to add this also? or the analysis of the e-commerce data will be done at db level?
https://developers.google.com/analytics/devguides/collection/gajs/gaTrackingEcommerce

Date: Thu, 1 Nov 2012 07:31:32 -0700

**Comment by mishimaltd** [comment]
Hi mate, we can do this from the db to be honest

On 1 Nov 2012, at 18:35, bertso notifications@github.com wrote:

Are we going to add this also? or the analysis of the e-commerce data will
be done at db level?
https://developers.google.com/analytics/devguides/collection/gajs/gaTrackingEcommerce

Date: Thu, 1 Nov 2012 07:31:32 -0700

**Comment by bertso** [comment]
Cool cool, just asking :-)

Date: Thu, 1 Nov 2012 12:15:30 -0700
