### ISSUE TITLE
Edit webdefault.xml to use UTF-8 encoding

### ISSUE THREAD

**Issue by mishimaltd** [citymenu/clickandeat#203]

**Comment by bertso** [comment]
What is the effect of this? I find it quite extrange that we have to write all the Spanish text escaping the Spanish characters inside the JSPs.. I have change all of them but somehow I think it will almost impossible to develop a massive site having to do that.

Date: Mon, 22 Oct 2012 06:29:16 -0700

**Comment by mishimaltd** [comment]
It won't break anything but might mean we don't have to escape everything.
The current escaped stuff would still work.

On 22 Oct 2012, at 14:38, bertso notifications@github.com wrote:

What is the effect of this? I find it quite extrange that we have to write
all the Spanish text escaping the Spanish characters inside the JSPs.. I
have change all of them but somehow I think it will almost impossible to
develop a massive site having to do that.

Date: Mon, 22 Oct 2012 06:29:16 -0700

**Comment by mishimaltd** [comment]
This is more to get the new fancy URL thing to work

On 22 Oct 2012, at 14:38, bertso notifications@github.com wrote:

What is the effect of this? I find it quite extrange that we have to write
all the Spanish text escaping the Spanish characters inside the JSPs.. I
have change all of them but somehow I think it will almost impossible to
develop a massive site having to do that.

Date: Mon, 22 Oct 2012 06:29:16 -0700

**Comment by bertso** [comment]
Cool. I might test it locally so that I don't have to escape everything :-)

Date: Mon, 22 Oct 2012 06:47:31 -0700

**Comment by bertso** [comment]
What would it do? Accept urls with funny characters?

Date: Mon, 22 Oct 2012 06:48:03 -0700

**Comment by mishimaltd** [comment]
Yeah give it a go

On 22 Oct 2012, at 14:48, bertso notifications@github.com wrote:

Cool. I might test it locally so that I don't have to escape everything :-)

Date: Mon, 22 Oct 2012 06:47:31 -0700

**Comment by mishimaltd** [comment]
Hopefully

On 22 Oct 2012, at 14:49, bertso notifications@github.com wrote:

What would it do? Accept urls with funny characters?

Date: Mon, 22 Oct 2012 06:48:03 -0700

**Comment by mishimaltd** [comment]
Hopefully I can fix this stuff so that the Spanish characters go straight
through

On 22 Oct 2012, at 14:49, bertso notifications@github.com wrote:

What would it do? Accept urls with funny characters?

Date: Mon, 22 Oct 2012 06:48:03 -0700

**Comment by bertso** [comment]
It makes no difference in the JSPs ma friend

Date: Mon, 22 Oct 2012 06:29:16 -0700

**Comment by mishimaltd** [comment]
Ok we need to do more  work :-)

On 22 Oct 2012, at 17:33, bertso notifications@github.com wrote:

It makes no difference in the JSPs ma friend

Date: Mon, 22 Oct 2012 06:29:16 -0700

**Comment by bertso** [comment]
Yep. I'll have a look

Date: Mon, 22 Oct 2012 09:36:05 -0700
