### ISSUE TITLE
Scrolling in the orders admin window

### ISSUE THREAD

**Issue by bertso** [citymenu/clickandeat#214]
I cannot scroll down in the Orders Admin window.

**Comment by mishimaltd** [comment]
Can you try clearing your cache/cookies etc, it works OK for me

**Comment by bertso** [comment]
Hi mate,The scrolling doesn't appear when you open an order that is close to the bottom of the screen and the login goes below the screen. Let me know if you don't have that problem. I have attached an image

Date: Tue, 30 Oct 2012 01:52:34 -0700

**Comment by mishimaltd** [comment]
Can't reproduce at all, sorry :-)
