### ISSUE TITLE
Special Offers

### ISSUE THREAD

**Issue by bertso** [citymenu/clickandeat#223]
When you have options in a special offer and you are ordering when you add the offer to the order you have to select the items. What happens here is that none are selected by default and then if you don't select one of them the "Done" doesn't work and you don't get an warning or anything.

Options: We select the first one by default or we warn them that they haven't selected one of the options.

Go to Xurreia Trebol special offers to see what I mean. post code 08037

Also if you don't enter a description in the options you get a null value which doesn't look right. For example I entered pizzas and there isn't a need to add a description so it looks a bit odd.

**Comment by mishimaltd** [comment]
Fixed, defaulting to first option and sorted out the null thing
