### ISSUE TITLE
Delay for the phone call to start

### ISSUE THREAD

**Issue by bertso** [citymenu/clickandeat#224]
I am not sure if this is as a result of all the code that i have added or if it was always like this, but you have the feeling that between receiving the call and the machine starting to speak it takes quite a while and it may some times be confused with a faulty call. Is it possible to add an extra step that just makes a noise straight away so you know that it is actually us, don't hang up, look for pen and paper and start writing..

**Comment by mishimaltd** [comment]
Is that testing locally or on the server?

On 7 Nov 2012, at 18:33, bertso notifications@github.com wrote:

I am not sure if this is as a result of all the code that i have added or
if it was always like this, but you have the feeling that between receiving
the call and the machine starting to speak it takes quite a while and it
may some times be confused with a faulty call. Is it possible to add an
extra step that just makes a noise straight away so you know that it is
actually us, don't hang up, look for pen and paper and start writing..

—
Reply to this email directly or view it on
GitHubhttps://github.com/mishimaltd/clickandeat/issues/224.

**Comment by bertso** [comment]
On the server

Date: Wed, 7 Nov 2012 10:37:49 -0800

**Comment by mishimaltd** [comment]
Unfortunately because it’s dynamic content we have to serve it up from the server, I don’t think there is anything we can do about this sadly.

**Comment by mishimaltd** [comment]
Fixed
