### ISSUE TITLE
#4 should repeat the address and customer details

### ISSUE THREAD

**Issue by bertso** [citymenu/clickandeat#225]
We should create another response message for those cases where the restaurant just wants to listen again to the users details. I am going to create the velocity template, I'll leave the easy part to you :-)

**Comment by mishimaltd** [comment]
Should we let them repeat just the order items as well?

On 8 Nov 2012, at 14:59, bertso notifications@github.com wrote:

We should create another response message for those cases where the
restaurant just wants to listen again to the users details. I am going to
create the velocity template, I'll leave the easy part to you :-)

—
Reply to this email directly or view it on
GitHubhttps://github.com/mishimaltd/clickandeat/issues/225.

**Comment by bertso** [comment]
I've just had a very interesting chat with me mate. Although there is a chance that the Restaurants may dictate finally the content of the messages etc we thought that the following could be the best formula to try to provide them with:
1) Introductions message. A bit more on this one laterWhat is now the full order divide it in 2) Here we thought that the best thing will be to start with:    "Hi you have an order for X pounds for the following address (Should it be for delivery). We believe that with this info the restaurant may be in a position to already reject the order an release the phone."3) Should they want to carry on, we say the Order number and client details4) Next, Full order
He was asking me if we could repeat the address details while in step 2) and then repeat the full order while in step 3)
We didn't discuss this, but it has occurred to me that maybe we can make 2) part of 1)
"Hi, this is click and eat, you have a new order for £60 to (deliver\collect), press any key to listen, 0 to cancel or hungup to deal with it using your email."Then move to step 3)
What do you think?
I believe that this will release the phone from unnecessary time being engage.

Date: Thu, 8 Nov 2012 07:24:53 -0800

**Comment by mishimaltd** [comment]
Yeah that sounds good mate

On 8 Nov 2012, at 16:13, bertso notifications@github.com wrote:

I've just had a very interesting chat with me mate. Although there is a
chance that the Restaurants may dictate finally the content of the messages
etc we thought that the following could be the best formula to try to
provide them with:
1) Introductions message. A bit more on this one laterWhat is now the full
order divide it in 2) Here we thought that the best thing will be to start
with: "Hi you have an order for X pounds for the following address (Should
it be for delivery). We believe that with this info the restaurant may be
in a position to already reject the order an release the phone."3) Should
they want to carry on, we say the Order number and client details4) Next,
Full order
He was asking me if we could repeat the address details while in step 2)
and then repeat the full order while in step 3)
We didn't discuss this, but it has occurred to me that maybe we can make 2)
part of 1)
"Hi, this is click and eat, you have a new order for £60 to
(deliver\collect), press any key to listen, 0 to cancel or hungup to deal
with it using your email."Then move to step 3)
What do you think?
I believe that this will release the phone from unnecessary time being
engage.

Date: Thu, 8 Nov 2012 07:24:53 -0800

**Comment by bertso** [comment]
Can you do this division or do you want me to have a go? You said before you were going to look into doing things differently also, in terms of putting the messages in the cache etc, didn't you?

Date: Thu, 8 Nov 2012 08:21:02 -0800

**Comment by mishimaltd** [comment]
I can do it mate. Do you mind adding that timing logging in on the velocity
service so we know how long it takes. Might influence how we approach the
issue.

On 8 Nov 2012, at 17:21, bertso notifications@github.com wrote:

Can you do this division or do you want me to have a go? You said before
you were going to look into doing things differently also, in terms of
putting the messages in the cache etc, didn't you?

Date: Thu, 8 Nov 2012 08:21:02 -0800

**Comment by bertso** [comment]
Yep. I'll do that now. Sorry I was at the house kicking some arsss. F***ng builders. On Monday I get the Polish Contingent   and hopefully things will change..
One question. You know this thing that you've done for the testing. What happens with  those orders? They are getting saved, aren't they? We should remove them somehow.

Date: Thu, 8 Nov 2012 09:31:05 -0800

**Comment by mishimaltd** [comment]
Yeah they get saved ill add a delete button on the orders view or maybe add
an order attribute to indicate its a test or fuck it and do both

On 8 Nov 2012, at 17:42, bertso notifications@github.com wrote:

Yep. I'll do that now. Sorry I was at the house kicking some arsss. F***ng
builders. On Monday I get the Polish Contingent and hopefully things will
change..
One question. You know this thing that you've done for the testing. What
happens with those orders? They are getting saved, aren't they? We should
remove them somehow.

Date: Thu, 8 Nov 2012 09:31:05 -0800
