### ISSUE TITLE
Order Total and delivery charges

### ISSUE THREAD

**Issue by bertso** [citymenu/clickandeat#230]
Having the Order Total and the delivery charges together is causing mayhem :-). Basically everyone is reporting that the discounts don't work, they actually do, but the way the total amount is displayed is confusing. They think they have reached the amount at which the discount should become available and they are logging it as bugs. Is there any way we can separate them? Or at least display the toral without the delivery charges somewhere so they stop reporting this as a bug.

**Comment by mishimaltd** [comment]
Sure I understand

On 18 Nov 2012, at 10:42, bertso notifications@github.com wrote:

Having the Order Total and the delivery charges together is causing mayhem
:-). Basically everyone is reporting that the discounts don't work, they
actually do, but the way the total amount is displayed is confusing. They
think they have reached the amount at which the discount should become
available and they are logging it as bugs. Is there any way we can separate
them? Or at least display the toral without the delivery charges somewhere
so they stop reporting this as a bug.

—
Reply to this email directly or view it on
GitHubhttps://github.com/mishimaltd/clickandeat/issues/230.

**Comment by mishimaltd** [comment]
Ill add an extra row for order items total before delivery charge and any
discounts

On 18 Nov 2012, at 10:42, bertso notifications@github.com wrote:

Having the Order Total and the delivery charges together is causing mayhem
:-). Basically everyone is reporting that the discounts don't work, they
actually do, but the way the total amount is displayed is confusing. They
think they have reached the amount at which the discount should become
available and they are logging it as bugs. Is there any way we can separate
them? Or at least display the toral without the delivery charges somewhere
so they stop reporting this as a bug.

—
Reply to this email directly or view it on
GitHubhttps://github.com/mishimaltd/clickandeat/issues/230.

**Comment by bertso** [comment]
cool

Date: Sun, 18 Nov 2012 02:46:57 -0800

**Comment by mishimaltd** [comment]
Done
