### ISSUE TITLE
Consolidation of the accounts with restaurants

### ISSUE THREAD

**Issue by bertso** [citymenu/clickandeat#38]
We need to build something to tell us for a certain date range how much money should be paid to the restaurants. This should be a result of the % we have to pay the restaurant for the online payments minus the % they have to pay us for those instances where the order was paid and collected at the restaurant, unless we are not going to allow people to pay at the restaurant.

**Comment by mishimaltd** [comment]
Hi Mate

All the order data is in the database so it will be no problem creating reports to get this kind of information out.

Was talking to Paula about the workflow stuff and she thinks that the 20 minute auto-cancellation of an order is a good idea but it is way too long. She was saying that basically if you placed an order for a take-away and then 20 minutes later you got an email saying that the order could not be completed you would be so pissed off that you would be very unlikely to ever use the site again. I think we can add an additional step whereby if the order is not confirmed after 5 minutes we send an email to the customer saying something like:

"We are really sorry, the restaurant is very busy taking orders and has not had a chance to respond to your order as yet, would you like to cancel the order now? You will not be charged for this order if you cancel"

That way we let the customer get out of the deal early. We can still auto-cancel after 20 minutes but the customer will be less pissed off as it's pretty clear that we have tried our best. We can always configure the 5 minutes to 10 minutes or whatever.

-----Original Message-----
From: bertso [mailto:reply@reply.github.com] 
Sent: 25 July 2012 20:21
To: Joe Pugh
Subject: [clickandeat] Consolidation of the accounts with restaurants (#38)

We need to build something to tell us for a certain date range how much money should be paid to the restaurants. This should be a result of the % we have to pay the restaurant for the online payments minus the % they have to pay us for those instances where the order was paid and collected at the restaurant, unless we are not going to allow people to pay at the restaurant.

---

Reply to this email directly or view it on GitHub:
https://github.com/mishimaltd/clickandeat/issues/38

**Comment by bertso** [comment]
Yep I thought I mentioned that in my green comments but obviously I just dream it :-). Yep 20 mins is ridiculous, 5 tops, before you have segregated so much saliva that you may actually consider going to the restaurant and give them a bit..
