### ISSUE TITLE
Get an Amazon s3 account to store all static assets for the site

### ISSUE THREAD

**Issue by mishimaltd** [citymenu/clickandeat#39]
All static files such as images, js files, css files, etc should be stored on Amazon s3. The web pages we serve should have links to these resources from the s3 locations. This will significantly reduce the load on the Heroku web servers and let us serve more requests at once.

**Comment by bertso** [comment]
Is this a standard practice? What would be the cost associated to this?

**Comment by mishimaltd** [comment]
Hi Mate, yes its generally a good idea. The costs are absolutely tiny. Amazon charge $0.01 per 10,000 get requests and the browser caches the files once read. Say we have about 20 static resources we'll get charged $0.01 for every 500 users who access the site per month. Even if the site was very busy like 2,500 unique customers per day it would still work out at only 2500 \* 20 \* 31 = 1,550,000 GET requests per month which works out at 1,550,000 / 10,000 \* $0.01 = $1.5 per month, so around £1.20 a month max.

It will really help take the load off the application server, we would probably save money by reducing the load and not needing to run as many web processes in Heroku.

**Comment by bertso** [comment]
OK, it sounds as if we can afford that :-)

**Comment by mishimaltd** [comment]
http://conorjpower.com/2010/03/16/s3-deploy-jets3t-maven/

How to integrate syncing files to s3 as part of the maven build

**Comment by mishimaltd** [comment]
Created the account on amazon, added read policy for all users so we can link on the site. Uploaded all the stuff but it is not uploading it with the correct mime type, will look at the jets3t stuff as this should just work automatically

**Comment by mishimaltd** [comment]
Add this to the sync properties:
acl=PUBLIC_READ

**Comment by mishimaltd** [comment]
Also try a newer version:
ar uf synchronize-0.8.0.jar mime.types
    jar uf jetS3t-0.8.0.jar mime.types

**Comment by mishimaltd** [comment]
All working

**Comment by mishimaltd** [comment]
All working
