### ISSUE TITLE
Error when saving new restaurant. Follow steps below

### ISSUE THREAD

**Issue by bertso** [citymenu/clickandeat#69]
- Create the restaurant and save
- Add Category – Press Save Changes [Edit Menu Category window]
- Add Item – Press Save Changes [Edit Menu Item window]
- Press Save Changes [Restaurant window] and I get the following error

E11000 duplicate key error index: app4576581.restaurants.$restaurantId dup key: { : "00000330" }; nested exception is com.mongodb.MongoException$DuplicateKey: E11000 duplicate key error index: app4576581.restaurants.$restaurantId dup key: { : "00000330" }

**Comment by mishimaltd** [comment]
Cheers mate fixed now and redeployed

I have done the toppings bit but not the display part yet I'll do that
tomorrow

On 22 Aug 2012, at 23:05, bertso notifications@github.com wrote:
- Create the restaurant and save
- Add Category – Press Save Changes [Edit Menu Category window]
- Add Item – Press Save Changes [Edit Menu Item window]
- Press Save Changes [Restaurant window] and I get the following error

E11000 duplicate key error index: app4576581.restaurants.$restaurantId dup
key: { : "00000330" }; nested exception is
com.mongodb.MongoException$DuplicateKey: E11000 duplicate key error index:
app4576581.restaurants.$restaurantId dup key: { : "00000330" }

—
Reply to this email directly or view it on
GitHubhttps://github.com/mishimaltd/clickandeat/issues/69.
