### ISSUE TITLE
The scrollbar in the Menu Item grid does not work

### ISSUE THREAD

**Issue by bertso** [citymenu/clickandeat#71]
When you add items in the menu item grid once you have filled up all the screen with items you cannot reach newly created ones using the scroll you have to resize the screen so that you can see it. The items get created and the scroll bar gets resized it just does not get to them. Enjoying my jetlag :-)

It's a bit strange because if I save the restaurant document and close and open again the scroll works.. not only with the existing items but if I create a new one it lets me get to it.. maybe the jetlag is getting to me.. I swear that it was doing it with more than one category

**Comment by mishimaltd** [comment]
It should auto scroll, I'll check the page configuration.

You can drag and drop rows in the category and items views if you want to reorder them.

**Comment by mishimaltd** [comment]
It works fine for me, can you try clearing your browser cache?

**Comment by bertso** [comment]
I have cleared the browsers cache and it still happens. It is a bit of a pain but you have to create a new category and then add items until you reach the point where the scroll needs to be used. As I mentioned before, once you save and close the restaurant document then the scrolling works fine.

**Comment by mishimaltd** [comment]
I'm really sorry mate I just can't reproduce this in any environment

**Comment by bertso** [comment]
OK, I'll test it again and if I can reproduce it we can do it over the phone together :-)
Date: Fri, 24 Aug 2012 02:22:22 -0700
