### ISSUE TITLE
Menu Categories region resize

### ISSUE THREAD

**Issue by bertso** [citymenu/clickandeat#78]
I think that the west region containing the Menu Categories could go all the way down to the bottom and the divide the section on the right to display the list items and the Edit Menu.. That way when you have lots of categories you don't have to scroll down them, I found that annoying when I created one of the menues. Obviously this is a nice to have but I had the feeling that you were messing around with the layout of the admin..

**Comment by mishimaltd** [comment]
leave for now, will revisit whole admin bit once we are live
