### ISSUE TITLE
Wrong title when editing an special offer

### ISSUE THREAD

**Issue by bertso** [citymenu/clickandeat#84]
I was editing a discount and went back to the special offers and when editing the special offer document it says edit discount

**Comment by mishimaltd** [comment]
On 14 Sep 2012, at 15:55, bertso notifications@github.com wrote:

I was editing a discount and went back to the special offers and when
editing the special offer document it says edit discount

—
Reply to this email directly or view it on
GitHubhttps://github.com/mishimaltd/clickandeat/issues/84.

**Comment by mishimaltd** [comment]
Fixed
