### ISSUE TITLE
Change the loading spinny

### ISSUE THREAD

**Issue by mishimaltd** [citymenu/clickandeat#93]
Make it a little dialog with a message like 'Please wait...
Keep the spinny alive when doing checkout(), etc (basically anwhere where there is an ajax call then a url redirect, want to show the spinny during the url redirect)

**Comment by mishimaltd** [comment]
http://ajaxload.info/

**Comment by bertso** [comment]
Use the pac man one, with the butlers head :-)

Date: Wed, 17 Oct 2012 01:17:14 -0700

**Comment by mishimaltd** [comment]
Done
