### ISSUE TITLE
Need to provide additional information for address search

### ISSUE THREAD

**Issue by mishimaltd** [citymenu/clickandeat#96]
For the spanish address lookup we need to enter the street number, street name and postcode in order to get a good search result.

We need a way to validate the input for the restaurant. We can force the selection there by having a field for street number, one for street name and one for postcode and have all of them as required fields. When we save the record we can validate that we are able to resolve it to a Google location.

When a user enters their address details for delivery we can force them to enter the same data but for just doing the search we should capture as much information as possible. Have a hint field something like "255 This Street, 40000" then we parse the data as well as we can.

**Comment by mishimaltd** [comment]
Functionally working, need to finish links to suggested addresses and then its done.

**Comment by mishimaltd** [comment]
I am going to put a validation component on the server side to handle the address lookup, let me know if you think this is OK:

I will make the first line of the address and the postcode required fields so you can't save a restaurant without entering them. When you save a restaurant I will do a location lookup using the information from the first line and the postcode. If I do not get an exact match from google then I will return a validation error. I think this is reasonable as we need the restaurant information to be accurate and you will always have enough of an address to get this kind of detail. We just need street name, number and postcode to get a bang on address.

Let me know if you can think of any issues with this, maybe we can relax it a bit and just show a warning?

**Comment by bertso** [comment]
I am up for the tough approach, we need the restaurant address to be accurate, so unless we get a list of restaurants where it is impossible to save the document I wouldn't relax it. This is the 4th Reigh :|)

Date: Wed, 19 Sep 2012 02:33:10 -0700

**Comment by mishimaltd** [comment]
I'm with you :-)

On 19 Sep 2012, at 10:44, bertso notifications@github.com wrote:

I am up for the tough approach, we need the restaurant address to be
accurate, so unless we get a list of restaurants where it is impossible to
save the document I wouldn't relax it. This is the 4th Reigh :|)

Date: Wed, 19 Sep 2012 02:33:10 -0700
